name: Deploy to SFTP Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: access-5016253559.webspace-host.com
        username: a549875
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: ./
        remote_path: /homepages/31/d4298451771/htdocs/wordpress/wp-content/plugins/vectorize-wp/
        port: 22
